files: '(screenpy|examples)/*'
fail_fast: false
repos:
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3.9
- repo: https://github.com/timothycrosley/isort
  rev: 5.6.4
  hooks:
  - id: isort
    language_version: python3.9
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    language_version: python3.9
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
    language_version: python3.9
    additional_dependencies: ["PyHamcrest>=2.0.0,<2.1", "pytest>=5.4.0,<5.5", "allure-pytest>=2.8.0,<2.9", "selenium>=3.141.0,<3.142", "pyotp>=2.3.0,<2.4.0"]
    files: ^screenpy/
- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: pylint --max-line-length=88 --disable=bad-continuation --disable=no-self-use --disable=too-few-public-methods --disable=invalid-name --disable=wrong-import-order --disable=import-error --disable=super-init-not-called --disable=duplicate-code --disable=logging-format-interpolation --disable=logging-fstring-interpolation
    language: system
    types: [python]
